version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "05:00"
  open-pull-requests-limit: 10
