before:
  hooks:
    - go mod download
builds:
- id: main
  main: .
  binary: gursht
  env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  - image_templates:
      - "ghcr.io/eyenx/gursht:{{ .Tag }}"
      - "ghcr.io/eyenx/gursht:v{{ .Major }}"
      - "ghcr.io/eyenx/gursht:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/eyenx/gursht:latest"
    build_flag_templates:
      - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/eyenx/{{.ProjectName}}/main/README.md"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
    extra_files:
      - etc/passwd
