repos:
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-beta.5
    hooks:
      - id: go-fmt
      - id: go-vet-mod
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: forbid-new-submodules
