version: '3.3'

services:
  app:
    image: ghcr.io/eyenx/gursht
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_ENABLED=true
      - SHORTURL_HOST=https://shortener.example.com

  redis:
    image: redis:alpine
